### ISSUE TITLE
IMEI es null al subir rutas

### ISSUE THREAD

**Issue by oxcar** [codeandoxalapa/mapmap#10]
En ocasiones, al subir rutas no se recibe correctamente el IMEI (es null). Esto puede deberse a que:

* No es posible obtenerlo a traves del API de Android
* No se envía correctamente desde el teléfono
* No se recibe en el servidor por otros motivos

**Comment by categulario** [comment]
quizá vale la pena repensar toda esta cuestión del ID del teléfono. Generar un ID por dispositivo que no esté conectado con el IMEI por cuestiones de privacidad pero sí con algunos datos del usuario usados para el regisro de una cuenta (por uniformidad y consistencia).

Esto está relacionado con #5

**Comment by oxcar** [comment]
Sí, de acuerdo con @categulario.

**Comment by oxcar** [comment]
No se recomienda solicitar el IMEI si no es necesario.

https://developer.android.com/training/articles/user-data-ids

<img width="734" alt="Screenshot 2022-12-19 at 23 07 39" src="https://user-images.githubusercontent.com/2067516/208535762-acb7294e-e0d5-4444-a70f-ff64710f45d7.png">

**Comment by oxcar** [comment]
La recomendación es usar:
CaptureService.imei = Secure.getString(getBaseContext().getContentResolver(), Secure.ANDROID_ID);
