### ISSUE TITLE
Organización del código, limpieza de ficheros

### ISSUE THREAD

**Issue by oxcar** [codeandoxalapa/mapmap#12]
Este repositorio contiene dos proyectos:
* Una App de Android
* Una aplicación web

Ambas deberían estar en carpetas independientes, no anidadas.

Además se versionaron ficheros de Eclipse que no deberían versionarse.

**Comment by categulario** [comment]
quizá valdría la pena incluso separar los proyectos en sendos repositorios

**Comment by oxcar** [comment]
Podría ser.

Aunque en este caso, como la App no sirve de mucho sin el servidor y al revés, tiene sentido que sea un monorepo.

**Comment by categulario** [comment]
pienso más bien en los flujos de desarrollo. Teniendo repositorios separados se pueden administrar también independientemente y tener cada uno su readme en raíz y su propia organización, lo cual tiene sentido porque serán tecnologías y hasta equipos diferentes.

**Comment by oxcar** [comment]
Sí, de acuerdo.
