### ISSUE TITLE
Verificar compatibilidad para instalación con diferentes versiones de SO Android

### ISSUE THREAD

**Issue by jmbecerril** [codeandoxalapa/mapmap#3]
Al intentar instalar la aplicación en un dispositivo android desde la tienda oficial indica: “**Tu dispositivo no es compatible con esta versión”**

_Ejemplo: Tablet Acer con Android 4.4.2_

**Comment by oxcar** [comment]
Aunque la app está hecha con un API viejo de Android, y te da una advertencia de que es una versión vieja, en general no hay problema para ejecutarla en teléfonos modernos.

Desde Android Studio es posible generar un APK, subirlo a un URL pública y apuntar el navegador del teléfono a esa URL para instalarla. Aparecen varias advertencias de seguridad y de que se trata de una versión antigua de Android y que ya no recibe mantenimiento, pero se puede instalar y usar.
