### ISSUE TITLE
instrucciones de setup y compilación

### ISSUE THREAD

**Issue by categulario** [codeandoxalapa/mapmap#4]
Igual y para los que le saben chido al android está papa, pero para uno que es nuevo en estas artes sería lindo como tener un "necesitas esto" y "haces esto" y ya puedes estar desarrollando la aplicación

**Comment by jmbecerril** [comment]
Totalmente de acuerdo! Vamos a hacer una actualización a README para colocar información sobre el proyecto y los "to must and to do" para ejecutar y desarrollar con el proyecto.
