### ISSUE TITLE
Envío de rutas

### ISSUE THREAD

**Issue by cesariux23** [codeandoxalapa/mapmap#5]
Al darle enviar, a donde es que se envia la información? a transitWand?
Cómo es que se calcula el ID de las unidades al registrarse? tambien se registran directamente a transitWand?, baje transitwand, le di registrar y me proporciono el mismo ID

**Comment by cesariux23** [comment]
Ya cheque, map map manda la información a transitwand

**Comment by jmbecerril** [comment]
1.- Al enviar las rutas al servidor se envía información al servidor de Transitwand y a Codeando Xalapa

2.- El ID de las unidades se obtiene del dispositivo, es único ... así que podrías instalar MapMap o Transitwand y vas a obtener el mismo ID porque sigue siendo el mismo dispositivo.

> _CaptureService.imei = telephonyManager.getDeviceId();_

Así se obtiene ID del dispositivo https://developer.android.com/reference/android/telephony/TelephonyManager.html

**Comment by cesariux23** [comment]
Haaaaaa

**Comment by cesariux23** [comment]
En realidad me refería a el id de 6 digitos que te pide transitWand para ver las rutas subidas, y que se genera aleatoria mente [aquí](https://github.com/cesariux23/backback/blob/master/app/models/Phone.java#L39) .

**Comment by jmbecerril** [comment]
Voy a seguir revisando el código porque todavía me parece un poco confuso cómo se utiliza el imei y el unitId en la app de backend

**Comment by categulario** [comment]
Estaba viendo el código de `Phone.java` que señaló @cesariux23 y está bien raro... como que le sobran cosas

**Comment by jmbecerril** [comment]
Lo voy a seguir analizando .. mi confusión es con el imei y unitId .. por qué utilizar los dos? .. creo sólo sería necesario utilizar uno de ellos, pero eso es lo que estoy revisando :)

**Comment by oxcar** [comment]
Efectivamente, el teléfono tiene dos IDs. El IMEI se usa internamente para identificar el teléfono, pero además se crea un unitID que es el que se le da al usuario para que pueda buscar sus rutas subidas al servidor. 

Además cuando un usuario sube sus rutas envía el IMEI como parámetro, no el unitId.

Sería posible usar un solo ID, pero el IMEI es claramente más largo y le costaría más a los usuarios usarlo a la hora de extraer las rutas del servidor.
